/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./src/components/ArticleItem/index.vue')['default']
    ArticleNavigator: typeof import('./src/components/ArticleNavigator/index.vue')['default']
    Drawer: typeof import('./src/components/Drawer/index.vue')['default']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/components/LoginOrRegDialog/LoginForm/index.vue')['default']
    LoginOrRegDialog: typeof import('./src/components/LoginOrRegDialog/index.vue')['default']
    NavBar: typeof import('./src/components/NavBar/index.vue')['default']
    OverLay: typeof import('./src/components/OverLay/index.vue')['default']
    PersonCard: typeof import('./src/components/PersonCard/index.vue')['default']
    PreviewImage: typeof import('./src/components/PreviewImage/index.vue')['default']
    RegBox: typeof import('./src/components/RegBox/index.vue')['default']
    RegForm: typeof import('./src/components/LoginOrRegDialog/RegForm/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidentify: typeof import('./src/components/Sidentify/index.vue')['default']
  }
}
